{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "alfresco-java-service.fullname" . }}
{{- end }}
  labels:
    {{- include "alfresco-java-service.labels" . | nindent 4 }}
data:
  application.properties: |-
{{- range $key, $value := .Values.configMap }}
    {{ $key }}={{ tpl $value . }}
{{- end }}
{{- end }}
