{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "alfresco-java-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "alfresco-java-service.fullname" . }}
subjects:
- kind: ServiceAccount
{{- if .Values.service.name }}
  name: {{ .Values.service.name }}
{{- else }}
  name: {{ template "alfresco-java-service.fullname" . }}
{{- end }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
